checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: './bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
    environment:
        php:
            version: '7.1'

filter:
    paths: ["src"]
    excluded_paths:
        - "spec/"
        - "tests/"
#
#tools:
#    external_code_coverage:
#        #timeout: 300
#        runs: 2
